spring:
  application:
    name: SocialFileService
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/social
    username: postgres
    password: 1212
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
    fetchRegistry: true
    registerWithEureka: true
server:
  port: 4