server:
  port: 9

spring:
  application:
    name: SocialSearchService
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/social
    username: postgres
    password: 1212
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    hostname: localhost